"""
2025 MLB Opening Day Lineups (primary starters by position)
Source: C:\\Users\\fw_ya\\Desktop\\MLBレギュラー.txt (Opening Day 2025 context)
Name format: "Last, First" to match bat_tracking() data.
Note: Where platoons exist, the primary/Opening Day starter is listed.
"""

POSITIONS = ["C", "1B", "2B", "3B", "SS", "LF", "CF", "RF", "DH"]

# Dict: team_code -> {position: "Last, First"}
MLB_LINEUPS_2025: dict[str, dict[str, str]] = {
    # --- American League East ---
    "NYY": {
        "C":  "Wells, Austin",
        "1B": "Goldschmidt, Paul",
        "2B": "Chisholm Jr., Jazz",
        "3B": "Cabrera, Oswaldo",
        "SS": "Volpe, Anthony",
        "LF": "Dominguez, Jasson",
        "CF": "Bellinger, Cody",
        "RF": "Judge, Aaron",
        "DH": "Rice, Ben",
    },
    "BOS": {
        "C":  "Wong, Connor",
        "1B": "Casas, Triston",
        "2B": "Campbell, Kristian",
        "3B": "Bregman, Alex",
        "SS": "Story, Trevor",
        "LF": "Duran, Jarren",
        "CF": "Rafaela, Ceddanne",
        "RF": "Abreu, Wilyer",
        "DH": "Devers, Rafael",
    },
    "TOR": {
        "C":  "Kirk, Alejandro",
        "1B": "Guerrero Jr., Vladimir",
        "2B": "Gimenez, Andres",
        "3B": "Clement, Ernie",
        "SS": "Bichette, Bo",
        "LF": "Santander, Anthony",
        "CF": "Straw, Myles",
        "RF": "Springer, George",
        "DH": "Schneider, Davis",
    },
    "BAL": {
        "C":  "Rutschman, Adley",
        "1B": "Mountcastle, Ryan",
        "2B": "Holliday, Jackson",
        "3B": "Westburg, Jordan",
        "SS": "Henderson, Gunnar",
        "LF": "Cowser, Colton",
        "CF": "Mullins, Cedric",
        "RF": "O'Neill, Tyler",
        "DH": "O'Hearn, Ryan",
    },
    "TBR": {
        "C":  "Jansen, Danny",
        "1B": "Diaz, Yandy",
        "2B": "Lowe, Brandon",
        "3B": "Caminero, Junior",
        "SS": "Walls, Taylor",
        "LF": "Morel, Christopher",
        "CF": "DeLuca, Jonny",
        "RF": "Lowe, Josh",
        "DH": "Aranda, Jonathan",
    },
    # --- American League Central ---
    "CLE": {
        "C":  "Naylor, Bo",
        "1B": "Santana, Carlos",
        "2B": "Arias, Gabriel",
        "3B": "Ramirez, Jose",
        "SS": "Rocchio, Brayan",
        "LF": "Kwan, Steven",
        "CF": "Thomas, Lane",
        "RF": "Jones, Nolan",
        "DH": "Manzardo, Kyle",
    },
    "MIN": {
        "C":  "Jeffers, Ryan",
        "1B": "France, Ty",
        "2B": "Castro, Willi",
        "3B": "Miranda, Jose",
        "SS": "Correa, Carlos",
        "LF": "Bader, Harrison",
        "CF": "Buxton, Byron",
        "RF": "Wallner, Matt",
        "DH": "Larnach, Trevor",
    },
    "DET": {
        "C":  "Rogers, Jake",
        "1B": "Keith, Colt",
        "2B": "Torres, Gleyber",
        "3B": "Ibanez, Andy",
        "SS": "Baez, Javier",
        "LF": "Greene, Riley",
        "CF": "Margot, Manuel",
        "RF": "Carpenter, Kerry",
        "DH": "Torkelson, Spencer",
    },
    "CWS": {
        "C":  "Lee, Korey",
        "1B": "Vaughn, Andrew",
        "2B": "Sosa, Lenyn",
        "3B": "Vargas, Miguel",
        "SS": "Amaya, Jacob",
        "LF": "Taylor, Michael A.",
        "CF": "Robert Jr., Luis",
        "RF": "Slater, Austin",
        "DH": "Benintendi, Andrew",
    },
    "KCR": {
        "C":  "Perez, Salvador",
        "1B": "Pasquantino, Vinnie",
        "2B": "Massey, Michael",
        "3B": "India, Jonathan",
        "SS": "Witt Jr., Bobby",
        "LF": "Melendez, MJ",
        "CF": "Isbel, Kyle",
        "RF": "Renfroe, Hunter",
        "DH": "Garcia, Maikel",
    },
    # --- American League West ---
    "HOU": {
        "C":  "Diaz, Yainer",
        "1B": "Walker, Christian",
        "2B": "Dubon, Mauricio",
        "3B": "Paredes, Isaac",
        "SS": "Pena, Jeremy",
        "LF": "Altuve, Jose",
        "CF": "Meyers, Jake",
        "RF": "Smith, Cam",
        "DH": "Alvarez, Yordan",
    },
    "TEX": {
        "C":  "Heim, Jonah",
        "1B": "Burger, Jake",
        "2B": "Semien, Marcus",
        "3B": "Jung, Josh",
        "SS": "Seager, Corey",
        "LF": "Langford, Wyatt",
        "CF": "Taveras, Leody",
        "RF": "Garcia, Adolis",
        "DH": "Pederson, Joc",
    },
    "SEA": {
        "C":  "Raleigh, Cal",
        "1B": "Raley, Luke",
        "2B": "Moore, Dylan",
        "3B": "Polanco, Jorge",
        "SS": "Crawford, J.P.",
        "LF": "Arozarena, Randy",
        "CF": "Rodriguez, Julio",
        "RF": "Robles, Victor",
        "DH": "Garver, Mitch",
    },
    "LAA": {
        "C":  "O'Hoppe, Logan",
        "1B": "Schanuel, Nolan",
        "2B": "Rengifo, Luis",
        "3B": "Moncada, Yoan",
        "SS": "Anderson, Tim",
        "LF": "Ward, Taylor",
        "CF": "Trout, Mike",
        "RF": "Adell, Jo",
        "DH": "Soler, Jorge",
    },
    "OAK": {
        "C":  "Langeliers, Shea",
        "1B": "Soderstrom, Tyler",
        "2B": "Gelof, Zack",
        "3B": "Urshela, Gio",
        "SS": "Wilson, Jacob",
        "LF": "Rooker, Brent",
        "CF": "Bleday, JJ",
        "RF": "Butler, Lawrence",
        "DH": "Andujar, Miguel",
    },
    # --- National League East ---
    "ATL": {
        "C":  "Baldwin, Drake",
        "1B": "Olson, Matt",
        "2B": "Albies, Ozzie",
        "3B": "Riley, Austin",
        "SS": "Arcia, Orlando",
        "LF": "Profar, Jurickson",
        "CF": "Harris II, Michael",
        "RF": "Kelenic, Jarred",
        "DH": "Ozuna, Marcell",
    },
    "NYM": {
        "C":  "Torrens, Luis",
        "1B": "Alonso, Pete",
        "2B": "Acuna, Luisangel",
        "3B": "Vientos, Mark",
        "SS": "Lindor, Francisco",
        "LF": "Nimmo, Brandon",
        "CF": "Siri, Jose",
        "RF": "Soto, Juan",
        "DH": "Winker, Jesse",
    },
    "PHI": {
        "C":  "Realmuto, J.T.",
        "1B": "Harper, Bryce",
        "2B": "Stott, Bryson",
        "3B": "Bohm, Alec",
        "SS": "Turner, Trea",
        "LF": "Kepler, Max",
        "CF": "Marsh, Brandon",
        "RF": "Castellanos, Nick",
        "DH": "Schwarber, Kyle",
    },
    "MIA": {
        "C":  "Fortes, Nick",
        "1B": "Mervis, Matt",
        "2B": "Lopez, Otto",
        "3B": "Norby, Connor",
        "SS": "Edwards, Xavier",
        "LF": "Stowers, Kyle",
        "CF": "Hill, Derek",
        "RF": "Conine, Griffin",
        "DH": "Bride, Jonah",
    },
    "WSN": {
        "C":  "Ruiz, Keibert",
        "1B": "Lowe, Nathaniel",
        "2B": "Garcia Jr., Luis",
        "3B": "DeJong, Paul",
        "SS": "Abrams, CJ",
        "LF": "Wood, James",
        "CF": "Young, Jacob",
        "RF": "Crews, Dylan",
        "DH": "Bell, Josh",
    },
    # --- National League Central ---
    "CHC": {
        "C":  "Amaya, Miguel",
        "1B": "Busch, Michael",
        "2B": "Hoerner, Nico",
        "3B": "Shaw, Matt",
        "SS": "Swanson, Dansby",
        "LF": "Happ, Ian",
        "CF": "Crow-Armstrong, Pete",
        "RF": "Tucker, Kyle",
        "DH": "Suzuki, Seiya",
    },
    "MIL": {
        "C":  "Contreras, William",
        "1B": "Hoskins, Rhys",
        "2B": "Turang, Brice",
        "3B": "Capra, Vinny",
        "SS": "Ortiz, Joey",
        "LF": "Chourio, Jackson",
        "CF": "Mitchell, Garrett",
        "RF": "Frelick, Sal",
        "DH": "Yelich, Christian",
    },
    "STL": {
        "C":  "Herrera, Ivan",
        "1B": "Contreras, Willson",
        "2B": "Gorman, Nolan",
        "3B": "Arenado, Nolan",
        "SS": "Winn, Masyn",
        "LF": "Nootbaar, Lars",
        "CF": "Scott II, Victor",
        "RF": "Walker, Jordan",
        "DH": "Donovan, Brendan",
    },
    "CIN": {
        "C":  "Trevino, Jose",
        "1B": "Encarnacion-Strand, Christian",
        "2B": "McLain, Matt",
        "3B": "Candelario, Jeimer",
        "SS": "De La Cruz, Elly",
        "LF": "Lux, Gavin",
        "CF": "Friedl, TJ",
        "RF": "Fraley, Jake",
        "DH": "Steer, Spencer",
    },
    "PIT": {
        "C":  "Bart, Joey",
        "1B": "Rodriguez, Endy",
        "2B": "Gonzales, Nick",
        "3B": "Hayes, Ke'Bryan",
        "SS": "Kiner-Falefa, Isiah",
        "LF": "Pham, Tommy",
        "CF": "Cruz, Oneil",
        "RF": "Reynolds, Bryan",
        "DH": "McCutchen, Andrew",
    },
    # --- National League West ---
    "LAD": {
        "C":  "Smith, Will",
        "1B": "Freeman, Freddie",
        "2B": "Kim, Hyeseong",
        "3B": "Muncy, Max",
        "SS": "Betts, Mookie",
        "LF": "Conforto, Michael",
        "CF": "Edman, Tommy",
        "RF": "Hernandez, Teoscar",
        "DH": "Ohtani, Shohei",
    },
    "SDP": {
        "C":  "Diaz, Elias",
        "1B": "Arraez, Luis",
        "2B": "Cronenworth, Jake",
        "3B": "Machado, Manny",
        "SS": "Bogaerts, Xander",
        "LF": "Sheets, Gavin",
        "CF": "Merrill, Jackson",
        "RF": "Tatis Jr., Fernando",
        "DH": "O'Hearn, Ryan",
    },
    "ARI": {
        "C":  "Moreno, Gabriel",
        "1B": "Naylor, Josh",
        "2B": "Marte, Ketel",
        "3B": "Suarez, Eugenio",
        "SS": "Perdomo, Geraldo",
        "LF": "Gurriel Jr., Lourdes",
        "CF": "McCarthy, Jake",
        "RF": "Carroll, Corbin",
        "DH": "Grichuk, Randal",
    },
    "SFG": {
        "C":  "Bailey, Patrick",
        "1B": "Wade Jr., LaMonte",
        "2B": "Fitzgerald, Tyler",
        "3B": "Chapman, Matt",
        "SS": "Adames, Willy",
        "LF": "Ramos, Heliot",
        "CF": "Lee, Jung Hoo",
        "RF": "Yastrzemski, Mike",
        "DH": "Flores, Wilmer",
    },
    "COL": {
        "C":  "Stallings, Jacob",
        "1B": "Toglia, Michael",
        "2B": "Farmer, Kyle",
        "3B": "McMahon, Ryan",
        "SS": "Tovar, Ezequiel",
        "LF": "Martini, Nick",
        "CF": "Doyle, Brenton",
        "RF": "Beck, Jordan",
        "DH": "Bryant, Kris",
    },
}

# All 30 teams are now covered — no fallback needed
MISSING_TEAMS: list[str] = []
